Added component example with listeners
georg3103/react-underhood-boilerplate pull request #2
Opened 2020-07-20 19:46 UTC by georg3103

2020-07-22 15:31 UTC, oceandrama requested changes
Нужно изменить функцию сортировки алфавита

2020-07-22 15:31 UTC, oceandrama commented on samples/List.jsx
> +    e.preventDefault();
Кажется, что можно не вызывать эту функцию, поведение не должно измениться

2020-07-22 15:31 UTC, oceandrama commented on samples/List.jsx
> +    e.preventDefault();
И тут тоже

2020-07-22 15:31 UTC, oceandrama commented on samples/List.jsx
> +      items: [...newLetter, ...items]
Тут не до конца, наверное понято задание
Нужно сохранить порядок букв в исходной строке, изменив только те, что были в инпуте
На входных данных (["а", "б", "в", "г", "д"], "гба") должно получиться ["г","б","в","а","д"]

2020-07-22 15:31 UTC, oceandrama commented on webpack.config.js
> +        use: [
Лоадер сам берёт конфиг из файла конфигурации, можно его тут не дублировать

2020-07-22 15:31 UTC, oceandrama commented on babel.config.js
> +      "@babel/transform-react-jsx",
А что не работало со старой настройкой?

2020-07-22 16:23 UTC, georg3103 commented on samples/List.jsx
> +      items: [...newLetter, ...items]
Наверное, опечатка в том, что должно вернуться из функции.
Правильно ли я понимаю, что функция должна принять (["а", "б", "в", "г", "д"], "гба")  и вернуть  ["г","б","а","в","д"]

2020-07-22 16:32 UTC, oceandrama commented on samples/List.jsx
> +      items: [...newLetter, ...items]
Нет, должно вернуться именно ["г","б","в","а","д"]
Буквы "в" и "д" остаются на своих местах, т.к. их нет в строке. Остальные выстраиваются в том порядке, в котором они шли в строке

2020-07-25 15:55 UTC, georg3103 commented on babel.config.js
> +      "@babel/transform-react-jsx",
не запускались методы
foo = () => {
   ...
  };

2020-07-28 11:41 UTC, merged