added profiler
georg3103/react-underhood-boilerplate pull request #3
Opened 2020-07-22 15:17 UTC by georg3103

2020-07-28 07:28 UTC, oceandrama requested changes
Нужно доработать профайлер, реализовать функцию сравнения пропсов
И проверь, пожалуйста, ещё раз, нужны ли вызовы preventDefault во всех обработчиках

2020-07-28 07:28 UTC, oceandrama commented on src/updateDomProperties.js
> +import shallowEqual from "shallowequal";
Эту функцию предлагается реализовать самостоятельно

2020-07-28 07:28 UTC, oceandrama commented on src/updateDomProperties.js
> +      window.performance_profiler.incrementWrongRender();
Тут обращаешься через `window`, а в других местах импортируешь

2020-07-28 07:28 UTC, oceandrama commented on src/index.js
> +import("./profiler");
А зачем он здесь?

2020-07-28 07:28 UTC, oceandrama commented on src/profiler.js
> +    this.statistics[name] = this.statistics.time[name]
Кажется, ты изменяешь не то поле. Складываешь `statistics.time[name]`, а записываешь в `statistics[name]`

2020-07-28 07:28 UTC, oceandrama commented on src/profiler.js
> +const profiler = {
А где методы для отключения сбора статистики?

2020-07-28 11:41 UTC, merged

2020-07-30 14:55 UTC, georg3103 commented on src/updateDomProperties.js
> +      window.performance_profiler.incrementWrongRender();
Я правильно понимаю, что необходимо сперва проверить существование профайлера в window, а потом уже собирать статистику?
Если да, то нужно на вызов каждого метода профайлера делать эту проверку. Получается, как-то коряво. Есть какой-то адекватный способ это сделать?

2020-07-30 14:59 UTC, georg3103 commented on src/index.js
> +import("./profiler");
Идея была в том, чтобы сработало
window.performance_profiler =
  process.env.NODE_ENV === "production" ? {} : profiler;
Но, видимо, это сделано неправильно. Есть ли адекватный способ добавить профайлер в window?
Также, файл профайлер не является модулем и сильно завязан на окружение из-а связи с window.
Есть ли смысл пытаться его как-то переписать в виде независимого модуля? Или это глупо?

2020-07-30 15:00 UTC, georg3103 commented on src/profiler.js
> +const profiler = {
Есть методы stopTracking и clear. Или о каком методе отключения сбора статистики идет речь? Что он должен делать?

2020-07-30 15:28 UTC, oceandrama commented on src/index.js
> +import("./profiler");
Этот код выполнится при первом обращении. Ты же используешь методы трекинга в других файлах, там и произойдет инициализация

2020-07-30 15:29 UTC, oceandrama commented on src/index.js
> +import("./profiler");
Переписывать не нужно, он выглядит так, как должен

2020-07-30 15:32 UTC, oceandrama commented on src/profiler.js
> +const profiler = {
startTracking и stopTracking должны включать некий флажок, который отвечает за то, трекается ли время или нет. Это нужно, чтобы оценить влияния замеров на производительность. И отдельно у тебя есть методы, которые начинают и заканчивают замер (сейчас они как раз называется startTracking и stopTracking)

2020-07-30 15:35 UTC, oceandrama commented on src/updateDomProperties.js
> +      window.performance_profiler.incrementWrongRender();
Нет, этого не нужно делать. Сам профайлер - это обычный объект, который сохраняет в себя статистику. То, что он при этом сохраняется в window - это детали его реализации, про которые внешним компонентам знать не нужно